export const enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  DATABASE_ERROR = 'DATABASE_ERROR',
  OPENAI_ERROR = 'OPENAI_ERROR',
  CORSAIR_ERROR = 'CORSAIR_ERROR',
  GMAIL_NOT_CONNECTED = 'GMAIL_NOT_CONNECTED',
  CALENDAR_NOT_CONNECTED = 'CALENDAR_NOT_CONNECTED',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
